### ISSUE TITLE
Where is the circular view you show in the screenshot?

### ISSUE THREAD

**Issue by goelv** [Triggertrap/TTCounterLabel#1]
In the sample project, there is no circular view which counts up/down with the time as you have shown in the screenshot. 

Was that just an example shot, or did you create that view?

**Comment by Ross-Gibson** [comment]
HI,

The screenshot for this control is taken from version 2.1.1 of our Triggertrap iOS app to show the control in use. The circular countdown view is not part of the TTCounterLabel control. We may release a control for this component in the future, but in the mean time if you'd like a similar control, take a look at this https://github.com/danielamitay/DACircularProgress

Hope that helps.

**Comment by goelv** [comment]
Thanks. DACircularProgress looks pretty solid.

**Comment by goelv** [comment]
@Ross-Gibson I found another similar library https://github.com/tiagomnh/THCircularProgressView.

**Comment by zzz6519003** [comment]
will you os Triggertrap pls T.T
