### ISSUE TITLE
Usable in Swift?

### ISSUE THREAD

**Issue by iamgp** [Triggertrap/TTCounterLabel#10]
Im trying to get this working in a swift file.

I have downloaded TTCounterLabel.h/m and TTTAttributedLabel.h/m and have added it into my project. I have added `#import TTCounterLabel.h` to my bridged header and everything is working fine counting up.

However I'd like it to count down, and I'm having some problems, something to do with the following enum:

``` c
typedef NS_ENUM(NSInteger, kCountDirection){
    kCountDirectionUp = 0,
    kCountDirectionDown 
};
```

I've tried using this code in the swift file but it failed saying that `Int.Type does not have a member named kCountDirectionDown`

``` c
label.startValue = 60000 // <-- This works fine
label.countDirection = .kCountDirectionDown 

//I've also tried
label.countDirection = kCountDirection.kCountDirectionDown
label.countDirection = kCountDirection.Down
label.countDirection = .Down
```

Am I doing something wrong, or can I not use this with swift?
Thanks.

**Comment by Valentin-Kalchev** [comment]
Hey iamgp, 

In Swift you need to use the raw value as the Objective-C enum is of NSInteger type:

label.countDirection = kCountDirection.CountDirectionDown.rawValue

You were almost there! Hope that helps!

**Comment by iamgp** [comment]
Fantastic, that works.

Final question, how do I get the delegate functional?

I have:

```c
class RDNewTimerViewController: UIViewController, TTCounterLabelDelegate { 
    @IBOutlet weak var timerLabel: TTCounterLabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        timerLabel.startValue = 10000
        timerLabel.countDirection = kCountDirection.CountDirectionDown.rawValue
        
        self.customiseAppearance()
    }
    
    func countdownDidEndForSource(source: TTCounterLabel!) {
        print("countdown finished")
    }
```
I have also ctrl-drag from the label to the class instance and set the delegate that way.

Thanks for all your help!

**Comment by iamgp** [comment]
Fantastic, thanks :)
