### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by torminen** [Triggertrap/TTCounterLabel#2]
Hi, Ross.
Great control, but I found some bug.

TTCounterLabel.m - line 136:
<code>[self setValue:(_startValue - milliSecs)];</code>

Here you're setting unsigned long value. You need to be sure about value is not negative. Such situation may appear after application was in background. And you know what happen with unsigned variables after setting negative value in C :)

**Comment by Ross-Gibson** [comment]
Thanks for report torminen, glad your using the control and like it.

I'll get this fixed soon and release the updated CocoaPod.

**Comment by Ross-Gibson** [comment]
This is now fixed in version 1.0.3
