### ISSUE TITLE
Question about TTCounterLabel in app background state.

### ISSUE THREAD

**Issue by EvgenyKarkan** [Triggertrap/TTCounterLabel#4]
Thank you for the work you done to create this component! It awesome!

Testing TTCounterLabel's timer I found that it can be reset to zero  & stopped when the application is in the background state. 
The maximum value which I was able to detect - about 42 hours. At the same time - I repeatedly faced with the fact that the counter stops a couple of hours later (after its start) while application in the background.
I used my iPad 4 with iOS 7.0.4 for my tests.

Steps to reproduce:
1. Start counter
2. Press "Home" button --> (app in background)
3. After some period of time - touch the app icon --> (app in foreground)
4. Result: sometimes counter is reset to zero & stopped. (approximate probability - 2-3 times of 10)

So my question is:
What am I doing wrong using TTCounterLabel?
Is it possible to use it without unexpected stops on app background mode?

waiting for your answer,
Best wishes.

**Comment by Ross-Gibson** [comment]
HI Evgeny,

We're glad you like the control, and thanks for the extensive testing you have done to find this issue.

This control has been specifically developed for use in our Triggertrap Mobile iOS App, which is not able to run in the background for audio reasons. As a result we have not developed this control to work whilst running in the background.

If you have an idea of how to improve or fix this issue then we would gladly accept a pull request from you and include in a future release of our app.

Thanks again for your question, and we're sorry we can't help further.

All the best,

Ross
